### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trsh** [alex47/Dual-Kawase-Blur#2]
Question still is how use the offset in the iteration to the image really blurry?

Could not understand from code :/

**Comment by alex47** [comment]
I don't really understand the question.
If you want more info on how this whole thing works take a look at this presentation slide: https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf

I used this as a reference when I created this project

**Comment by trsh** [comment]
@alex47 the document doesn't imply offset variable (page 21). That what I'm asking. For what and how to use it in the pass iteration.

**Comment by alex47** [comment]
The bigger the offset the blurrier the image gets.
But a too big offset value can cause artifacts. So you have to find the right value before it starts artifacting. I'm sure a mathematical equation exists for this, but I decided to choose the values manually.
With more iterations you can choose higher offset values.
Have you tried running my program? Have you tried playing with iteration and offset values?

**Comment by trsh** [comment]
Yes, on win 10 it gave me an error about QT missing orsmth. But i got the idea now, tnx!

**Comment by alex47** [comment]
I updated the executable release.
Please try it again:
https://github.com/alex47/Dual-Kawase-Blur/releases/latest

**Comment by trsh** [comment]
Jip works now

**Comment by trsh** [comment]
@alex47 btw is there some special property/setting/option for buffers/drawing so this blur works properly? Im trying to implement in my project and it kind of works, but even with 8 iters 5 offset (where the image should become extreme blured) it's ... so so
![blur_w](https://user-images.githubusercontent.com/3727523/70661306-a6e08880-1c6c-11ea-9d97-8080702ab87c.png)

**Comment by trsh** [comment]
@alex47  Here https://www.shadertoy.com/view/ttc3Wr I try only down-sample in 5 passes. Isn't the effect to weak? What Im doing wrong?

**Comment by alex47** [comment]
That's because you completely miss the point.
In that shadertoy you don't downsample at all. You **try** some downsampling but then do no upsampling. We have to have the same number of upsampling as downsampling.

Here is a more correct implementation: https://www.shadertoy.com/view/3td3W8

Ideally the texture sizes should also change between the passes, but we can't do that in shadertoy.

**Comment by trsh** [comment]
`Ideally the texture sizes should also change between the passes, but we can't do that in shadertoy`

Can you @alex47 please explain how it should change? Does it have something todo with /2 and *2 you added to Shader? Where do you do the sizing in your code?

P.S i did only add add downsampling (no up) just to show you that the effect is almost not noticeable in that stage.

**Comment by trsh** [comment]
Ouch I think its here `m_FBO_vector.append(new QOpenGLFramebufferObject(m_imageToBlur.size() / qPow(2, i), QOpenGLFramebufferObject::CombinedDepthStencil, GL_TEXTURE_2D));` ? What could be the workaround if I can't resize the buffer texture?

**Comment by alex47** [comment]
The next downsample size is always a quarter of the previous pass, and the upsample is the opposite
For example for 4 iterations texture sizes would be:

- 1024x768 - original image
- 512x384 - downsample iteration 1
- 256x192 - downsample iteration 2
- 128x96 - downsample iteration 3
- 64x48 - downsample iteration 4
- 128x96 - upsample iteration 1
- 256x192 - upsample iteration 2
- 512x384 - upsample iteration 3
- 1024x768 - upsample iteration 4 (final output)

If you can't create different sized buffer textures then you are absolutely using the wrong tools.
The workaround is already in my shadertoy link, as shadertoy uses same texture sizes.
I really do not recommend using same texture sizes because of big performance impact.

**Comment by trsh** [comment]
I start to think this is wrong technique for my project. a) Its very hard to get in-between blurriness, because with every additional down-sample iteration it makes a very big jump. b) Controlling it with for example with a slider (blur strength), and increase / decrease gradually seems almost impossible. Maybe  still there is some crazy math that combines offset and iterations todo such thing, but for now seems rather not. Let me know if Im wrong.

**Comment by alex47** [comment]
You are right. Transition with this is not really possible.
If you really must have transition then I suggest you use kawase blur instead.
It uses no downsampling and can do transitions well.

Here is a sample implementation I made: https://www.shadertoy.com/view/Wlc3D4
It requires multiple passes. This one has 5 (shadertoy limitation).
Also make sure you use correct kernel sizes for the number of passes, else it looks distorted.
I ~~stole~~ borrowed the kernels from here: https://gist.github.com/pkonecki/4f80114b192e60dead65e2897fd1bc0d
The kernel is stored in the `i` variable in the shader.

**Comment by alex47** [comment]
or use gaussian blur if you really don't care about performance and want the best look

**Comment by trsh** [comment]
@alex47 i dont get the Kernel part. Your i variable 0.5, 1.5, 2.5, 2.5, 3,5. How does that relate to link you shared? its +0.5 because of the animation?

**Comment by alex47** [comment]
it's +0.5 because we sample from between 4 pixels in one instruction, not just from 1 pixel

![](https://software.intel.com/sites/default/files/managed/f6/f9/Figure10.png)
> An example of 5-pass Kawase blur with 0, 1, 2, 2, 3 kernels, matching in output a 35x35 Gauss blur kernel. Marked in blue is 1 sample covering 4 pixels; marked in red is the destination pixel receiving averaged sum of those samples

it's exploiting a neat gpu trick

for more info read: https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms

**Comment by trsh** [comment]
Still don't get the +0.5 part :D. Its also not explained in your link.
